import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationProvider } from "@/context/NavigationContext";
import ClientSideJWTRefresher from "@/components/ClientSideJWTRefresher"; // path to the client-only component
import ClientSideRoleGuard from "@/components/ClientSideRoleGuard"; // ⬅️ Add this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavigationProvider>{children}</NavigationProvider>
        <ClientSideJWTRefresher /> {/* ✅ Client-only logic here */}
        <ClientSideRoleGuard /> {/* ✅ Add role guard globally */}
      </body>
    </html>
  );
}
