import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientSideJWTRefresher from "@/components/ClientSideJWTRefresher"; // path to the client-only component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSideJWTRefresher /> {/* ✅ Client-only logic here */}
        {children}
      </body>
    </html>
  );
}
